/**
 * Screenshots the served UI at real device sizes.
 *
 * Points a headless browser at a running `ghostr serve --http` and walks the
 * four tabs on each device. Deliberately not a mock: the page renders whatever
 * the vault actually returns, so a screenshot cannot show a screen the product
 * does not have.
 *
 *   node tools/ui-preview/shots.mjs <url-with-token> <out-dir>
 */
import { createRequire } from "node:module";
import { mkdir, writeFile } from "node:fs/promises";

// Resolved through `require` rather than a bare import so a globally installed
// Playwright works: ESM ignores NODE_PATH, and this tool is deliberately not a
// dependency of the workspace — a screenshot harness has no business in the
// build graph of a vault (CLAUDE.md §4.9).
const require = createRequire(import.meta.url);
const { chromium, devices } = require(
  process.env.PLAYWRIGHT_PATH ?? "playwright",
);

// Named for the device, because "428x926" tells a reviewer nothing about
// whether their own phone is covered.
const TARGETS = [
  { name: "iphone-13-pro-max", label: "iPhone 13 Pro Max", ...devices["iPhone 13 Pro Max"] },
  { name: "iphone-se", label: "iPhone SE (small)", ...devices["iPhone SE"] },
  { name: "pixel-7", label: "Pixel 7", ...devices["Pixel 7"] },
  { name: "ipad-mini", label: "iPad mini", ...devices["iPad Mini"] },
  {
    name: "desktop",
    label: "Desktop 1440",
    viewport: { width: 1440, height: 900 },
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
  },
];

const TABS = ["today", "quests", "score", "vault"];

const url = process.argv[2];
const outDir = process.argv[3] ?? "docs/ui/shots";
if (!url) {
  console.error("usage: shots.mjs <url-with-token> <out-dir>");
  process.exit(2);
}

await mkdir(outDir, { recursive: true });
const browser = await chromium.launch();

for (const target of TARGETS) {
  const { name, label, ...opts } = target;
  const context = await browser.newContext(opts);
  const page = await context.newPage();
  await page.goto(url, { waitUntil: "networkidle" });

  for (const tab of TABS) {
    // Click the real nav rather than calling the render function: what is
    // under review includes whether the control is reachable at this size.
    await page.click(`nav button[data-tab="${tab}"]`);
    // The tab paints a placeholder first and fills in after its fetch. Waiting
    // for the placeholder to go is what stops every shot being a "…".
    await page.waitForFunction(
      () => !document.getElementById("view").textContent.trim().startsWith("…"),
      null,
      { timeout: 5000 },
    ).catch(() => {});

    // A screenshot of the error card is still a screenshot, and a run that
    // writes twenty of them looks exactly like a run that worked. It has
    // happened: a stale server from an earlier run held the port, the page
    // answered every request with 401, and the gallery recorded the "no token"
    // screen as the product. The shot is only taken once the page has content.
    const text = await page.textContent("#view");
    for (const bad of ["This tab has no token", "The vault said no"]) {
      if (text.includes(bad)) {
        throw new Error(
          `${name}/${tab}: the page is showing an error, not the product — "${bad}". ` +
          `The vault or the token is wrong; fix that rather than keeping the shot.`,
        );
      }
    }
    if (!text.trim()) {
      throw new Error(`${name}/${tab}: the page rendered nothing.`);
    }

    await page.screenshot({ path: `${outDir}/${name}-${tab}.png`, fullPage: false });
  }
  console.log(`${label.padEnd(20)} ${opts.viewport.width}x${opts.viewport.height} @${opts.deviceScaleFactor}x`);
  await context.close();
}

await browser.close();

// The index is generated from the same lists that drove the browser, so it
// cannot describe a device that was not shot or miss one that was. A gallery
// maintained by hand beside a script is a gallery that goes stale on the first
// device somebody adds.
const TITLES = {
  today: "Today",
  quests: "Quests",
  score: "Fidelity",
  vault: "Vault",
};
const rel = outDir.split("/").pop();
let md = `<!-- generated by tools/ui-preview/shots.mjs — do not edit by hand -->

# UI, screen by screen

Every image is the real page, served by \`ghostr serve --http\` over a vault
built by \`tools/ui-preview/demo.sh\`. Nothing here is a mock: a screen the
product does not have cannot appear, and one that regressed cannot keep
looking right.

The notes and names in them are invented (CLAUDE.md §4.14).

[README.md](README.md) says how to regenerate these and what is known to be
wrong with them.

`;
for (const tab of TABS) {
  md += `## ${TITLES[tab] ?? tab}\n\n`;
  md += `| Device | |\n| --- | --- |\n`;
  for (const t of TARGETS) {
    const v = t.viewport;
    md += `| **${t.label}**<br>${v.width}×${v.height} @${t.deviceScaleFactor}x `;
    md += `| <img src="${rel}/${t.name}-${tab}.png" width="320"> |\n`;
  }
  md += `\n`;
}
await writeFile(`${outDir}/../gallery.md`, md);

console.log(`\nwrote ${TARGETS.length * TABS.length} shots to ${outDir}`);
console.log(`wrote ${outDir}/../gallery.md`);
