[package]
name = "ghostr-nostr"
description = "Ghostr nostr relay client and event codec for kinds 31780-31789."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ghostr-core = { workspace = true }
ghostr-crypto = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

[lints]
workspace = true
